package dao;

import models.Manager;
import util.BankRepository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Optional;

/**
 * Data Access Object (DAO) for the Manager entity.
 * Responsible for managing persistence in the MANAGER table.
 */
public class ManagerDao {
    /**
     * Inserts a new manager into the database.
     * The ID is automatically generated by Oracle.
     * * @param manager The Manager object (must already contain the passwordHash).
     * @throws SQLException In case of a database error (e.g., CPF/login already registered).
     */
    public boolean insertManager(Manager manager) {
        Connection connection = null;
        String sql = "INSERT INTO MANAGER (cpf, name, address, birth_date, \"USER\", password, register_date) " +
                     "VALUES (?, ?, ?, TO_DATE(?, 'DD/MM/YYYY'), ?, ?, SYSDATE)";

        try {
            connection = BankRepository.getConnection();

            try (PreparedStatement stmt = connection.prepareStatement(sql)) {
                stmt.setString(1, manager.getCpf());
                stmt.setString(2, manager.getName());
                stmt.setString(3, manager.getAddress());
                stmt.setString(4, manager.getDateOfBirth());
                stmt.setString(5, manager.getUser());
                stmt.setString(6, manager.getPassword());

                if (stmt.executeUpdate() > 0) {
                    BankRepository.commitTransaction(connection);
                    return true;
                } else {
                    BankRepository.rollbackTransaction(connection);
                    return false;
                }
            }
        } catch (SQLException e) {
            BankRepository.rollbackTransaction(connection);
            System.err.println("[ERRO DAO] - Falha ao cadastrar gerente: " + e.getMessage());
            return false;
        } finally {
            BankRepository.closeConnection(connection);
        }
    }

    public Optional<Manager> findManagerByUser(String user) throws SQLException {
        Connection connection = null;
        String sql = "SELECT id_manager, cpf, name, address, birth_date, \"USER\", password " +
                "FROM manager " +
                "WHERE \"USER\" = ?";

        try{
            connection = BankRepository.getConnection();
            try (PreparedStatement stmt = connection.prepareStatement(sql)) {
                stmt.setString(1, user);

                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        int id = rs.getInt("id_manager");
                        String cpfClient = rs.getString("cpf");
                        String name = rs.getString("name");
                        String address = rs.getString("address");
                        String birthDate = rs.getString("birth_date");
                        String managerUser = rs.getString("user");
                        String password = rs.getString("password");

                        Manager manager = new Manager(name, cpfClient, birthDate, address, managerUser,  password);
                        manager.setId(id);

                        return Optional.of(manager);
                    }
                }
            }
        } catch (SQLException e) {
            System.err.println("Erro ao buscar cliente: " + e.getMessage());
        } finally {
            BankRepository.closeConnection(connection);
        }
        return null;
    }
}
